In [347]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [348]:
X_train= pd.read_csv("training_set_features.csv")
X_train

,respondent_id,xyz_concern,xyz_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,...,income_poverty,marital_status,rent_or_own,employment_status,hhs_geo_region,census_msa,household_adults,household_children,employment_industry,employment_occupation
0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,Below Poverty,Not Married,Own,Not in Labor Force,oxchjgsf,Non-MSA,0.0,0.0,NaN,NaN
1,1,3.0,2.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,...,Below Poverty,Not Married,Rent,Employed,bhuqouqj,"MSA, Not Principle City",0.0,0.0,pxcmvdjn,xgwztkwe
2,2,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,"<= $75,000, Above Poverty",Not Married,Own,Employed,qufhixun,"MSA, Not Principle City",2.0,0.0,rucpziij,xtkaffoo
3,3,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,...,Below Poverty,Not Married,Rent,Not in Labor Force,lrircsnp,"MSA, Principle City",0.0,0.0,NaN,NaN
4,4,2.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,...,"<= $75,000, Above Poverty",Married,Own,Employed,qufhixun,"MSA, Not Principle City",1.0,0.0,wxleyezf,emcorrxb
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26702,26702,2.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,...,"<= $75,000, Above Poverty",Not Married,Own,Not in Labor Force,qufhixun,Non-MSA,0.0,0.0,NaN,NaN
26703,26703,1.0,2.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,"<= $75,000, Above Poverty",Not Married,Rent,Employed,lzgpxyit,"MSA, Principle City",1.0,0.0,fcxhlnwr,cmhcxjea
26704,26704,2.0,2.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,...,NaN,Not Married,Own,NaN,lzgpxyit,"MSA, Not Principle City",0.0,0.0,NaN,NaN
26705,26705,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,...,"<= $75,000, Above Poverty",Married,Rent,Employed,lrircsnp,Non-MSA,1.0,0.0,fcxhlnwr,haliazsg
26706,26706,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,"<= $75,000, Above Poverty",Married,Own,Not in Labor Force,mlyzmhmf,"MSA, Principle City",1.0,0.0,NaN,NaN

In [349]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26707 entries, 0 to 26706
Data columns (total 36 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   respondent_id                26707 non-null  int64
 1   xyz_concern                  26615 non-null  float64
 2   xyz_knowledge                26591 non-null  float64
 3   behavioral_antiviral_meds    26636 non-null  float64
 4   behavioral_avoidance         26499 non-null  float64
 5   behavioral_face_mask         26688 non-null  float64
 6   behavioral_wash_hands        26665 non-null  float64
 7   behavioral_large_gatherings  26620 non-null  float64
 8   behavioral_outside_home      26625 non-null  float64
 9   behavioral_touch_face        26579 non-null  float64
 10  doctor_recc_xyz              24547 non-null  float64
 11  doctor_recc_seasonal         24547 non-null  float64
 12  chronic_med_condition        25736 non-null  float64
 13  child_under_6_months         25887 non-null  float64
 14  health_worker                25903 non-null  float64
 15  health_insurance             14433 non-null  float64
 16  opinion_xyz_vacc_effective   26316 non-null  float64
 17  opinion_xyz_risk             26319 non-null  float64
 18  opinion_xyz_sick_from_vacc   26312 non-null  float64
 19  opinion_seas_vacc_effective  26245 non-null  float64
 20  opinion_seas_risk            26193 non-null  float64
 21  opinion_seas_sick_from_vacc  26170 non-null  float64
 22  age_group                    26707 non-null  object
 23  education                    25300 non-null  object
 24  race                         26707 non-null  object
 25  sex                          26707 non-null  object
 26  income_poverty               22284 non-null  object
 27  marital_status               25299 non-null  object
 28  rent_or_own                  24665 non-null  object
 29  employment_status            25244 non-null  object
 30  hhs_geo_region               26707 non-null  object
 31  census_msa                   26707 non-null  object
 32  household_adults             26458 non-null  float64
 33  household_children           26458 non-null  float64
 34  employment_industry          13377 non-null  object
 35  employment_occupation        13237 non-null  object
dtypes: float64(23), int64(1), object(12)
memory usage: 7.3+ MB

In [350]:
X_train = X_train.drop(['hhs_geo_region','employment_industry','employment_occupation'],axis= 1)
X_train

,respondent_id,xyz_concern,xyz_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,...,education,race,sex,income_poverty,marital_status,rent_or_own,employment_status,census_msa,household_adults,household_children
0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,< 12 Years,White,Female,Below Poverty,Not Married,Own,Not in Labor Force,Non-MSA,0.0,0.0
1,1,3.0,2.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,...,12 Years,White,Male,Below Poverty,Not Married,Rent,Employed,"MSA, Not Principle City",0.0,0.0
2,2,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,College Graduate,White,Male,"<= $75,000, Above Poverty",Not Married,Own,Employed,"MSA, Not Principle City",2.0,0.0
3,3,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,...,12 Years,White,Female,Below Poverty,Not Married,Rent,Not in Labor Force,"MSA, Principle City",0.0,0.0
4,4,2.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,...,Some College,White,Female,"<= $75,000, Above Poverty",Married,Own,Employed,"MSA, Not Principle City",1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26702,26702,2.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,...,Some College,White,Female,"<= $75,000, Above Poverty",Not Married,Own,Not in Labor Force,Non-MSA,0.0,0.0
26703,26703,1.0,2.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,College Graduate,White,Male,"<= $75,000, Above Poverty",Not Married,Rent,Employed,"MSA, Principle City",1.0,0.0
26704,26704,2.0,2.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,...,Some College,White,Female,NaN,Not Married,Own,NaN,"MSA, Not Principle City",0.0,0.0
26705,26705,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,...,Some College,Hispanic,Female,"<= $75,000, Above Poverty",Married,Rent,Employed,Non-MSA,1.0,0.0
26706,26706,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,Some College,White,Male,"<= $75,000, Above Poverty",Married,Own,Not in Labor Force,"MSA, Principle City",1.0,0.0

In [351]:
X_train.isna().sum()

respondent_id                      0
xyz_concern                       92
xyz_knowledge                    116
behavioral_antiviral_meds         71
behavioral_avoidance             208
behavioral_face_mask              19
behavioral_wash_hands             42
behavioral_large_gatherings       87
behavioral_outside_home           82
behavioral_touch_face            128
doctor_recc_xyz                 2160
doctor_recc_seasonal            2160
chronic_med_condition            971
child_under_6_months             820
health_worker                    804
health_insurance               12274
opinion_xyz_vacc_effective       391
opinion_xyz_risk                 388
opinion_xyz_sick_from_vacc       395
opinion_seas_vacc_effective      462
opinion_seas_risk                514
opinion_seas_sick_from_vacc      537
age_group                          0
education                       1407
race                               0
sex                                0
income_poverty                  4423
marital_status                  1408
rent_or_own                     2042
employment_status               1463
census_msa                         0
household_adults                 249
household_children               249
dtype: int64

In [352]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26707 entries, 0 to 26706
Data columns (total 33 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   respondent_id                26707 non-null  int64
 1   xyz_concern                  26615 non-null  float64
 2   xyz_knowledge                26591 non-null  float64
 3   behavioral_antiviral_meds    26636 non-null  float64
 4   behavioral_avoidance         26499 non-null  float64
 5   behavioral_face_mask         26688 non-null  float64
 6   behavioral_wash_hands        26665 non-null  float64
 7   behavioral_large_gatherings  26620 non-null  float64
 8   behavioral_outside_home      26625 non-null  float64
 9   behavioral_touch_face        26579 non-null  float64
 10  doctor_recc_xyz              24547 non-null  float64
 11  doctor_recc_seasonal         24547 non-null  float64
 12  chronic_med_condition        25736 non-null  float64
 13  child_under_6_months         25887 non-null  float64
 14  health_worker                25903 non-null  float64
 15  health_insurance             14433 non-null  float64
 16  opinion_xyz_vacc_effective   26316 non-null  float64
 17  opinion_xyz_risk             26319 non-null  float64
 18  opinion_xyz_sick_from_vacc   26312 non-null  float64
 19  opinion_seas_vacc_effective  26245 non-null  float64
 20  opinion_seas_risk            26193 non-null  float64
 21  opinion_seas_sick_from_vacc  26170 non-null  float64
 22  age_group                    26707 non-null  object
 23  education                    25300 non-null  object
 24  race                         26707 non-null  object
 25  sex                          26707 non-null  object
 26  income_poverty               22284 non-null  object
 27  marital_status               25299 non-null  object
 28  rent_or_own                  24665 non-null  object
 29  employment_status            25244 non-null  object
 30  census_msa                   26707 non-null  object
 31  household_adults             26458 non-null  float64
 32  household_children           26458 non-null  float64
dtypes: float64(23), int64(1), object(9)
memory usage: 6.7+ MB

In [353]:
X_train['health_insurance'].value_counts()

health_insurance
1.0    12697
0.0     1736
Name: count, dtype: int64

In [354]:
X_train = X_train.drop(['health_insurance','respondent_id'], axis=1)

In [355]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26707 entries, 0 to 26706
Data columns (total 31 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   xyz_concern                  26615 non-null  float64
 1   xyz_knowledge                26591 non-null  float64
 2   behavioral_antiviral_meds    26636 non-null  float64
 3   behavioral_avoidance         26499 non-null  float64
 4   behavioral_face_mask         26688 non-null  float64
 5   behavioral_wash_hands        26665 non-null  float64
 6   behavioral_large_gatherings  26620 non-null  float64
 7   behavioral_outside_home      26625 non-null  float64
 8   behavioral_touch_face        26579 non-null  float64
 9   doctor_recc_xyz              24547 non-null  float64
 10  doctor_recc_seasonal         24547 non-null  float64
 11  chronic_med_condition        25736 non-null  float64
 12  child_under_6_months         25887 non-null  float64
 13  health_worker                25903 non-null  float64
 14  opinion_xyz_vacc_effective   26316 non-null  float64
 15  opinion_xyz_risk             26319 non-null  float64
 16  opinion_xyz_sick_from_vacc   26312 non-null  float64
 17  opinion_seas_vacc_effective  26245 non-null  float64
 18  opinion_seas_risk            26193 non-null  float64
 19  opinion_seas_sick_from_vacc  26170 non-null  float64
 20  age_group                    26707 non-null  object
 21  education                    25300 non-null  object
 22  race                         26707 non-null  object
 23  sex                          26707 non-null  object
 24  income_poverty               22284 non-null  object
 25  marital_status               25299 non-null  object
 26  rent_or_own                  24665 non-null  object
 27  employment_status            25244 non-null  object
 28  census_msa                   26707 non-null  object
 29  household_adults             26458 non-null  float64
 30  household_children           26458 non-null  float64
dtypes: float64(22), object(9)
memory usage: 6.3+ MB

In [356]:
X_train['age_group'].value_counts()

age_group
65+ Years        6843
55 - 64 Years    5563
45 - 54 Years    5238
18 - 34 Years    5215
35 - 44 Years    3848
Name: count, dtype: int64

In [357]:
obj_X_train= X_train.select_dtypes(include=['object']).copy()
obj_X_train

,age_group,education,race,sex,income_poverty,marital_status,rent_or_own,employment_status,census_msa
0,55 - 64 Years,< 12 Years,White,Female,Below Poverty,Not Married,Own,Not in Labor Force,Non-MSA
1,35 - 44 Years,12 Years,White,Male,Below Poverty,Not Married,Rent,Employed,"MSA, Not Principle City"
2,18 - 34 Years,College Graduate,White,Male,"<= $75,000, Above Poverty",Not Married,Own,Employed,"MSA, Not Principle City"
3,65+ Years,12 Years,White,Female,Below Poverty,Not Married,Rent,Not in Labor Force,"MSA, Principle City"
4,45 - 54 Years,Some College,White,Female,"<= $75,000, Above Poverty",Married,Own,Employed,"MSA, Not Principle City"
...,...,...,...,...,...,...,...,...,...
26702,65+ Years,Some College,White,Female,"<= $75,000, Above Poverty",Not Married,Own,Not in Labor Force,Non-MSA
26703,18 - 34 Years,College Graduate,White,Male,"<= $75,000, Above Poverty",Not Married,Rent,Employed,"MSA, Principle City"
26704,55 - 64 Years,Some College,White,Female,NaN,Not Married,Own,NaN,"MSA, Not Principle City"
26705,18 - 34 Years,Some College,Hispanic,Female,"<= $75,000, Above Poverty",Married,Rent,Employed,Non-MSA
26706,65+ Years,Some College,White,Male,"<= $75,000, Above Poverty",Married,Own,Not in Labor Force,"MSA, Principle City"

In [358]:

from sklearn.preprocessing import OrdinalEncoder

# Identify categorical columns
categorical_columns = X_train.select_dtypes(include=['object']).columns.tolist()

# Initialize OrdinalEncoder
encoder = OrdinalEncoder()

# Fit and transform the categorical columns
encoded_values = encoder.fit_transform(X_train[categorical_columns])

# Create a DataFrame of encoded values with original column names
X_train_encoded = pd.DataFrame(encoded_values, columns=categorical_columns)

# Replace original categorical columns with encoded values
X_train[categorical_columns] = X_train_encoded

# print(X_train)

X_train.info()
X_train.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26707 entries, 0 to 26706
Data columns (total 31 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   xyz_concern                  26615 non-null  float64
 1   xyz_knowledge                26591 non-null  float64
 2   behavioral_antiviral_meds    26636 non-null  float64
 3   behavioral_avoidance         26499 non-null  float64
 4   behavioral_face_mask         26688 non-null  float64
 5   behavioral_wash_hands        26665 non-null  float64
 6   behavioral_large_gatherings  26620 non-null  float64
 7   behavioral_outside_home      26625 non-null  float64
 8   behavioral_touch_face        26579 non-null  float64
 9   doctor_recc_xyz              24547 non-null  float64
 10  doctor_recc_seasonal         24547 non-null  float64
 11  chronic_med_condition        25736 non-null  float64
 12  child_under_6_months         25887 non-null  float64
 13  health_worker                25903 non-null  float64
 14  opinion_xyz_vacc_effective   26316 non-null  float64
 15  opinion_xyz_risk             26319 non-null  float64
 16  opinion_xyz_sick_from_vacc   26312 non-null  float64
 17  opinion_seas_vacc_effective  26245 non-null  float64
 18  opinion_seas_risk            26193 non-null  float64
 19  opinion_seas_sick_from_vacc  26170 non-null  float64
 20  age_group                    26707 non-null  float64
 21  education                    25300 non-null  float64
 22  race                         26707 non-null  float64
 23  sex                          26707 non-null  float64
 24  income_poverty               22284 non-null  float64
 25  marital_status               25299 non-null  float64
 26  rent_or_own                  24665 non-null  float64
 27  employment_status            25244 non-null  float64
 28  census_msa                   26707 non-null  float64
 29  household_adults             26458 non-null  float64
 30  household_children           26458 non-null  float64
dtypes: float64(31)
memory usage: 6.3 MB

,xyz_concern,xyz_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,doctor_recc_xyz,...,education,race,sex,income_poverty,marital_status,rent_or_own,employment_status,census_msa,household_adults,household_children
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,...,1.0,3.0,0.0,2.0,1.0,0.0,1.0,2.0,0.0,0.0
1,3.0,2.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,...,0.0,3.0,1.0,2.0,1.0,1.0,0.0,0.0,0.0,0.0
2,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,...,2.0,3.0,1.0,0.0,1.0,0.0,0.0,0.0,2.0,0.0
3,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,...,0.0,3.0,0.0,2.0,1.0,1.0,1.0,1.0,0.0,0.0
4,2.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,...,3.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [359]:
import pandas as pd
from sklearn.impute import SimpleImputer

def impute_most_frequent_inplace(X_train):

    imputer = SimpleImputer(strategy='mean')

    # Transform the data in place
    X_train[X_train.columns] = imputer.fit_transform(X_train)

impute_most_frequent_inplace(X_train)

print(X_train)

       xyz_concern  xyz_knowledge  behavioral_antiviral_meds  \
0              1.0            0.0                        0.0
1              3.0            2.0                        0.0
2              1.0            1.0                        0.0
3              1.0            1.0                        0.0
4              2.0            1.0                        0.0
...            ...            ...                        ...
26702          2.0            0.0                        0.0
26703          1.0            2.0                        0.0
26704          2.0            2.0                        0.0
26705          1.0            1.0                        0.0
26706          0.0            0.0                        0.0

       behavioral_avoidance  behavioral_face_mask  behavioral_wash_hands  \
0                       0.0                   0.0                    0.0
1                       1.0                   0.0                    1.0
2                       1.0                   0.0                    0.0
3                       1.0                   0.0                    1.0
4                       1.0                   0.0                    1.0
...                     ...                   ...                    ...
26702                   1.0                   0.0                    0.0
26703                   1.0                   0.0                    1.0
26704                   1.0                   1.0                    1.0
26705                   0.0                   0.0                    0.0
26706                   1.0                   0.0                    0.0

       behavioral_large_gatherings  behavioral_outside_home  \
0                              0.0                      1.0
1                              0.0                      1.0
2                              0.0                      0.0
3                              1.0                      0.0
4                              1.0                      0.0
...                            ...                      ...
26702                          0.0                      1.0
26703                          0.0                      0.0
26704                          1.0                      0.0
26705                          0.0                      0.0
26706                          0.0                      0.0

       behavioral_touch_face  doctor_recc_xyz  ...  education  race  sex  \
0                   1.000000         0.000000  ...        1.0   3.0  0.0
1                   1.000000         0.000000  ...        0.0   3.0  1.0
2                   0.000000         0.220312  ...        2.0   3.0  1.0
3                   0.000000         0.000000  ...        0.0   3.0  0.0
4                   1.000000         0.000000  ...        3.0   3.0  0.0
...                      ...              ...  ...        ...   ...  ...
26702               0.000000         0.000000  ...        3.0   3.0  0.0
26703               0.000000         1.000000  ...        2.0   3.0  1.0
26704               1.000000         0.000000  ...        3.0   3.0  0.0
26705               0.677264         0.000000  ...        3.0   1.0  0.0
26706               0.000000         0.000000  ...        3.0   3.0  1.0

       income_poverty  marital_status  rent_or_own  employment_status  \
0            2.000000             1.0          0.0           1.000000
1            2.000000             1.0          1.0           0.000000
2            0.000000             1.0          0.0           0.000000
3            2.000000             1.0          1.0           1.000000
4            0.000000             0.0          0.0           0.000000
...               ...             ...          ...                ...
26702        0.000000             1.0          0.0           1.000000
26703        0.000000             1.0          1.0           0.000000
26704        0.547658             1.0          0.0           0.520401
26705        0.000000             0.0          1.0           0.000000
26706        0.000000             0.0          0.0           1.000000

       census_msa  household_adults  household_children
0             2.0               0.0                 0.0
1             0.0               0.0                 0.0
2             0.0               2.0                 0.0
3             1.0               0.0                 0.0
4             0.0               1.0                 0.0
...           ...               ...                 ...
26702         2.0               0.0                 0.0
26703         1.0               1.0                 0.0
26704         0.0               0.0                 0.0
26705         2.0               1.0                 0.0
26706         1.0               1.0                 0.0

[26707 rows x 31 columns]

In [360]:
X_test= pd.read_csv("test_set_features.csv")
X_test

,respondent_id,xyz_concern,xyz_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,...,income_poverty,marital_status,rent_or_own,employment_status,hhs_geo_region,census_msa,household_adults,household_children,employment_industry,employment_occupation
0,26707,2.0,2.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,...,"> $75,000",Not Married,Rent,Employed,mlyzmhmf,"MSA, Not Principle City",1.0,0.0,atmlpfrs,hfxkjkmi
1,26708,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,Below Poverty,Not Married,Rent,Employed,bhuqouqj,Non-MSA,3.0,0.0,atmlpfrs,xqwwgdyp
2,26709,2.0,2.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,...,"> $75,000",Married,Own,Employed,lrircsnp,Non-MSA,1.0,0.0,nduyfdeo,pvmttkik
3,26710,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,"<= $75,000, Above Poverty",Married,Own,Not in Labor Force,lrircsnp,"MSA, Not Principle City",1.0,0.0,NaN,NaN
4,26711,3.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,...,"<= $75,000, Above Poverty",Not Married,Own,Employed,lzgpxyit,Non-MSA,0.0,1.0,fcxhlnwr,mxkfnird
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26703,53410,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,...,NaN,NaN,NaN,NaN,dqpwygqj,"MSA, Principle City",1.0,1.0,NaN,NaN
26704,53411,3.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,...,Below Poverty,Married,Rent,Employed,qufhixun,Non-MSA,1.0,3.0,fcxhlnwr,vlluhbov
26705,53412,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,Below Poverty,Not Married,Rent,Not in Labor Force,qufhixun,"MSA, Not Principle City",1.0,0.0,NaN,NaN
26706,53413,3.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,...,"<= $75,000, Above Poverty",Married,Own,Not in Labor Force,bhuqouqj,"MSA, Not Principle City",1.0,0.0,NaN,NaN
26707,53414,2.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,...,NaN,Not Married,Rent,Employed,lrircsnp,"MSA, Principle City",0.0,0.0,NaN,xtkaffoo

In [361]:
X_test = X_test.drop(['hhs_geo_region','employment_industry','employment_occupation'],axis= 1)
X_test

,respondent_id,xyz_concern,xyz_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,...,education,race,sex,income_poverty,marital_status,rent_or_own,employment_status,census_msa,household_adults,household_children
0,26707,2.0,2.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,...,College Graduate,Hispanic,Female,"> $75,000",Not Married,Rent,Employed,"MSA, Not Principle City",1.0,0.0
1,26708,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,12 Years,White,Male,Below Poverty,Not Married,Rent,Employed,Non-MSA,3.0,0.0
2,26709,2.0,2.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,...,College Graduate,White,Male,"> $75,000",Married,Own,Employed,Non-MSA,1.0,0.0
3,26710,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,12 Years,White,Female,"<= $75,000, Above Poverty",Married,Own,Not in Labor Force,"MSA, Not Principle City",1.0,0.0
4,26711,3.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,...,12 Years,Black,Female,"<= $75,000, Above Poverty",Not Married,Own,Employed,Non-MSA,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26703,53410,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,...,NaN,White,Female,NaN,NaN,NaN,NaN,"MSA, Principle City",1.0,1.0
26704,53411,3.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,...,12 Years,White,Male,Below Poverty,Married,Rent,Employed,Non-MSA,1.0,3.0
26705,53412,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,Some College,White,Female,Below Poverty,Not Married,Rent,Not in Labor Force,"MSA, Not Principle City",1.0,0.0
26706,53413,3.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,...,Some College,White,Female,"<= $75,000, Above Poverty",Married,Own,Not in Labor Force,"MSA, Not Principle City",1.0,0.0
26707,53414,2.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,...,College Graduate,White,Female,NaN,Not Married,Rent,Employed,"MSA, Principle City",0.0,0.0

In [362]:
X_test.isna().sum()

respondent_id                      0
xyz_concern                       85
xyz_knowledge                    122
behavioral_antiviral_meds         79
behavioral_avoidance             213
behavioral_face_mask              19
behavioral_wash_hands             40
behavioral_large_gatherings       72
behavioral_outside_home           82
behavioral_touch_face            128
doctor_recc_xyz                 2160
doctor_recc_seasonal            2160
chronic_med_condition            932
child_under_6_months             813
health_worker                    789
health_insurance               12228
opinion_xyz_vacc_effective       398
opinion_xyz_risk                 380
opinion_xyz_sick_from_vacc       375
opinion_seas_vacc_effective      452
opinion_seas_risk                499
opinion_seas_sick_from_vacc      521
age_group                          0
education                       1407
race                               0
sex                                0
income_poverty                  4497
marital_status                  1442
rent_or_own                     2036
employment_status               1471
census_msa                         0
household_adults                 225
household_children               225
dtype: int64

In [363]:
X_test = X_test.drop(['health_insurance','respondent_id'], axis=1)

In [364]:
from sklearn.preprocessing import OrdinalEncoder

# Identify categorical columns
categorical_columns = X_test.select_dtypes(include=['object']).columns.tolist()

# Initialize OrdinalEncoder
encoder = OrdinalEncoder()

# Fit and transform the categorical columns
encoded_values = encoder.fit_transform(X_test[categorical_columns])

# Create a DataFrame of encoded values with original column names
X_test_encoded = pd.DataFrame(encoded_values, columns=categorical_columns)

# Replace original categorical columns with encoded values
X_test[categorical_columns] = X_test_encoded

# print(X_train)

X_test.info()
X_test.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26708 entries, 0 to 26707
Data columns (total 31 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   xyz_concern                  26623 non-null  float64
 1   xyz_knowledge                26586 non-null  float64
 2   behavioral_antiviral_meds    26629 non-null  float64
 3   behavioral_avoidance         26495 non-null  float64
 4   behavioral_face_mask         26689 non-null  float64
 5   behavioral_wash_hands        26668 non-null  float64
 6   behavioral_large_gatherings  26636 non-null  float64
 7   behavioral_outside_home      26626 non-null  float64
 8   behavioral_touch_face        26580 non-null  float64
 9   doctor_recc_xyz              24548 non-null  float64
 10  doctor_recc_seasonal         24548 non-null  float64
 11  chronic_med_condition        25776 non-null  float64
 12  child_under_6_months         25895 non-null  float64
 13  health_worker                25919 non-null  float64
 14  opinion_xyz_vacc_effective   26310 non-null  float64
 15  opinion_xyz_risk             26328 non-null  float64
 16  opinion_xyz_sick_from_vacc   26333 non-null  float64
 17  opinion_seas_vacc_effective  26256 non-null  float64
 18  opinion_seas_risk            26209 non-null  float64
 19  opinion_seas_sick_from_vacc  26187 non-null  float64
 20  age_group                    26708 non-null  float64
 21  education                    25301 non-null  float64
 22  race                         26708 non-null  float64
 23  sex                          26708 non-null  float64
 24  income_poverty               22211 non-null  float64
 25  marital_status               25266 non-null  float64
 26  rent_or_own                  24672 non-null  float64
 27  employment_status            25237 non-null  float64
 28  census_msa                   26708 non-null  float64
 29  household_adults             26483 non-null  float64
 30  household_children           26483 non-null  float64
dtypes: float64(31)
memory usage: 6.3 MB

,xyz_concern,xyz_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,doctor_recc_xyz,...,education,race,sex,income_poverty,marital_status,rent_or_own,employment_status,census_msa,household_adults,household_children
0,2.0,2.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,...,2.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0
1,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3.0,1.0,2.0,1.0,1.0,0.0,2.0,3.0,0.0
2,2.0,2.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,...,2.0,3.0,1.0,1.0,0.0,0.0,0.0,2.0,1.0,0.0
3,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,3.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
4,3.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0,0.0,1.0

In [365]:
import pandas as pd
from sklearn.impute import SimpleImputer

def impute_most_frequent_inplace(X_test):

    imputer = SimpleImputer(strategy='mean')

    # Transform the data in place
    X_test[X_test.columns] = imputer.fit_transform(X_test)

impute_most_frequent_inplace(X_test)

print(X_test)

       xyz_concern  xyz_knowledge  behavioral_antiviral_meds  \
0              2.0            2.0                        0.0
1              1.0            1.0                        0.0
2              2.0            2.0                        0.0
3              1.0            1.0                        0.0
4              3.0            1.0                        1.0
...            ...            ...                        ...
26703          1.0            1.0                        0.0
26704          3.0            1.0                        0.0
26705          0.0            1.0                        0.0
26706          3.0            1.0                        0.0
26707          2.0            1.0                        0.0

       behavioral_avoidance  behavioral_face_mask  behavioral_wash_hands  \
0                       1.0                   0.0                    1.0
1                       0.0                   0.0                    0.0
2                       0.0                   1.0                    1.0
3                       0.0                   0.0                    0.0
4                       1.0                   0.0                    1.0
...                     ...                   ...                    ...
26703                   1.0                   0.0                    1.0
26704                   1.0                   0.0                    1.0
26705                   0.0                   0.0                    0.0
26706                   1.0                   0.0                    1.0
26707                   0.0                   0.0                    1.0

       behavioral_large_gatherings  behavioral_outside_home  \
0                              1.0                      0.0
1                              0.0                      0.0
2                              1.0                      1.0
3                              0.0                      0.0
4                              1.0                      1.0
...                            ...                      ...
26703                          0.0                      0.0
26704                          1.0                      1.0
26705                          0.0                      0.0
26706                          0.0                      1.0
26707                          0.0                      0.0

       behavioral_touch_face  doctor_recc_xyz  ...  education  race  sex  \
0                        1.0              0.0  ...   2.000000   1.0  0.0
1                        0.0              0.0  ...   0.000000   3.0  1.0
2                        1.0              0.0  ...   2.000000   3.0  1.0
3                        0.0              1.0  ...   0.000000   3.0  0.0
4                        1.0              0.0  ...   0.000000   0.0  0.0
...                      ...              ...  ...        ...   ...  ...
26703                    1.0              1.0  ...   1.737006   3.0  0.0
26704                    1.0              0.0  ...   0.000000   3.0  1.0
26705                    0.0              0.0  ...   3.000000   3.0  0.0
26706                    0.0              0.0  ...   3.000000   3.0  0.0
26707                    1.0              1.0  ...   2.000000   3.0  0.0

       income_poverty  marital_status  rent_or_own  employment_status  \
0            1.000000        1.000000     1.000000           0.000000
1            2.000000        1.000000     1.000000           0.000000
2            1.000000        0.000000     0.000000           0.000000
3            0.000000        0.000000     0.000000           1.000000
4            0.000000        1.000000     0.000000           0.000000
...               ...             ...          ...                ...
26703        0.540678        0.463785     0.241205           0.519792
26704        2.000000        0.000000     1.000000           0.000000
26705        2.000000        1.000000     1.000000           1.000000
26706        0.000000        0.000000     0.000000           1.000000
26707        0.540678        1.000000     1.000000           0.000000

       census_msa  household_adults  household_children
0             0.0               1.0                 0.0
1             2.0               3.0                 0.0
2             2.0               1.0                 0.0
3             0.0               1.0                 0.0
4             2.0               0.0                 1.0
...           ...               ...                 ...
26703         1.0               1.0                 1.0
26704         2.0               1.0                 3.0
26705         0.0               1.0                 0.0
26706         0.0               1.0                 0.0
26707         1.0               0.0                 0.0

[26708 rows x 31 columns]

In [366]:
y_train= pd.read_csv("training_set_labels.csv")
y_train=y_train.drop(["respondent_id"], axis=1)
y_train

       xyz_vaccine  seasonal_vaccine
0                0                 0
1                0                 1
2                0                 0
3                0                 1
4                0                 0
...            ...               ...
26702            0                 0
26703            0                 0
26704            0                 1
26705            0                 0
26706            0                 0

[26707 rows x 2 columns]

In [367]:
y_train.isna().sum()

xyz_vaccine         0
seasonal_vaccine    0
dtype: int64

In [368]:
y_train['xyz_vaccine'].value_counts()

xyz_vaccine
0    21033
1     5674
Name: count, dtype: int64

In [369]:
y_train['seasonal_vaccine'].value_counts()

seasonal_vaccine
0    14272
1    12435
Name: count, dtype: int64

In [370]:
import xgboost as xgb
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import train_test_split

# Assuming you have X_train and y_train already loaded

# Split X_train and y_train into training and validation sets
X_train_split, X_val_split, y_train_split, y_val_split = train_test_split(X_train, y_train, test_size=0.2, random_state=42)

# Define parameters for XGBoost
params = {
    'objective': 'binary:logistic',   # Use logistic regression for binary classification
    'eval_metric': 'auc',             # Evaluation metric: ROC AUC
    'eta': 0.1,                       # Learning rate
    'max_depth': 5,                   # Maximum depth of each tree
    'subsample': 0.8,                 # Subsample ratio of the training instances
    'colsample_bytree': 0.8,          # Subsample ratio of columns when constructing each tree
    'seed': 42                        # Random seed for reproducibility
}

# Initialize XGBoost models
bst_first = xgb.XGBClassifier(**params)
bst_second = xgb.XGBClassifier(**params)

# Train the model for the first output feature
bst_first.fit(X_train_split, y_train_split['xyz_vaccine'])

# Train the model for the second output feature
bst_second.fit(X_train_split, y_train_split['seasonal_vaccine'])

# Predict probabilities on validation set
y_pred_proba_first = bst_first.predict_proba(X_val_split)[:, 1]
y_pred_proba_second = bst_second.predict_proba(X_val_split)[:, 1]

# Calculate ROC AUC for each output feature on validation set
auc_first = roc_auc_score(y_val_split['xyz_vaccine'], y_pred_proba_first)
auc_second = roc_auc_score(y_val_split['seasonal_vaccine'], y_pred_proba_second)

# Print ROC AUC scores
print("ROC AUC for first output feature (xyz_vaccine):", auc_first)
print("ROC AUC for second output feature (seasonal_vaccine):", auc_second)

ROC AUC for first output feature (xyz_vaccine): 0.8387367739875113
ROC AUC for second output feature (seasonal_vaccine): 0.8617776633712215

In [372]:
import xgboost as xgb
from sklearn.metrics import roc_auc_score


dtrain_first = xgb.DMatrix(X_train, label=y_train['xyz_vaccine']) 
dtrain_second = xgb.DMatrix(X_train, label=y_train['seasonal_vaccine'])  

# Define parameters for XGBoost
params = {
    'objective': 'binary:logistic',   # Use logistic regression for binary classification
    'eval_metric': 'auc',             # Evaluation metric: ROC AUC
    'eta': 0.1,                       # Learning rate
    'max_depth': 5,                   # Maximum depth of each tree
    'subsample': 0.8,                 # Subsample ratio of the training instances
    'colsample_bytree': 0.8,          # Subsample ratio of columns when constructing each tree
    'seed': 42                        # Random seed for reproducibility
}

# Train the model for the first output feature
num_round = 100  # Number of boosting rounds (iterations)
bst_first = xgb.train(params, dtrain_first, num_round)

# Train the model for the second output feature
bst_second = xgb.train(params, dtrain_second, num_round)

# Make predictions on the training set for both output features
y_pred_proba_first = bst_first.predict(dtrain_first)
y_pred_proba_second = bst_second.predict(dtrain_second)

# Example: Assuming y_train is the true labels for X_train
# Replace y_train with your actual true labels if available
y_true_first = y_train['xyz_vaccine']
y_true_second = y_train['seasonal_vaccine']

# Calculate ROC AUC for each output feature on the training set
auc_first = roc_auc_score(y_true_first, y_pred_proba_first)
auc_second = roc_auc_score(y_true_second, y_pred_proba_second)

# Print or use the ROC AUC scores as needed
print("ROC AUC for first output feature on training set:", auc_first)
print("ROC AUC for second output feature on training set:", auc_second)




# Convert X_test into DMatrix format for XGBoost (for testing)
dtest = xgb.DMatrix(X_test)

# Make predictions on X_test for both output features
y_pred_proba_first = bst_first.predict(dtest)
y_pred_proba_second = bst_second.predict(dtest)

# Example: Print or use the predictions as needed
print("Predictions for first output feature on X_test:")
print(y_pred_proba_first)

print("\nPredictions for second output feature on X_test:")
print(y_pred_proba_second)

ROC AUC for first output feature on training set: 0.8797564717819845
ROC AUC for second output feature on training set: 0.8832802292774445
Predictions for first output feature on X_test:
[0.11485401 0.04165234 0.5647848  ... 0.119539   0.03020575 0.479818  ]

Predictions for second output feature on X_test:
[0.19223763 0.03750454 0.8355966  ... 0.15803404 0.36964908 0.5917728 ]